- name: Verify inventory variables
  hosts: all
  gather_facts: false
  tasks:
    - name: Display variables
      debug:
        msg:
          server_name: "{{ server_name }}"
          port: "{{ port }}"
          env: "{{ environment }}"
